site_name: 人的操作系统
site_dir: site
docs_dir: docs



# Copyright
copyright: '人的操作系统 版权所有 Copyright © 2025 caozuoxitong.ren All Rights Reserved.'

# 导航
nav:
  - 简介: index.md
  - 技术文章:
    - 用GitHub Pages搭建个人网站: 20250118-githubpages.md

# 主题设置
theme:
  name: material
  features:
    - navigation.tabs
  palette:
      # Toggle light mode
      - scheme: default
        primary: white
        accent: red
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Toggle dark mode
      - scheme: slate
        primary: black
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to light mode
  language: zh
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'