# Project Information
site_name: 人的操作系统
site_description: 探索和构建人的操作系统
site_author: Human Operate System Lab
site_url: https://caozuoxitong.ren
site_dir: site
docs_dir: docs
copyright: '人的操作系统 版权所有 Copyright © 2018-2025 caozuoxitong.ren All Rights Reserved.'

# Contents 导航
nav:
  - 首页: index.md
  - 性命篇: xingmingpian.md
  - 价值篇: jiazhipian.md
  - 化育篇: 
      - 识:
          # - 物理领域: education/physics.md
          # - 生命领域: education/life.md
          - 文明领域: education/civilization.md
  - 道路篇: daolupian.md
  - 建树篇: jianshupian.md
  # - 筑基篇:
    # - 身:
    #   - 经络系统:  
    #     - 筋膜学理论: human-body/theory/fasciology/fasciology.md
    #     - 人体经络系统: human-body/theory/meridian-system/meridian-system.md   
    #     - 阴阳理论: human-body/theory/yin-yang-theory/yin-yang-theory.md
    #     - 五行理论: human-body/theory/five-elements-theory/five-elements-theory.md
    #   - 环境影响: huanjingyingxiang.md
    #   - 养生之道:
    #     - 少林洗髓易筋经: human-body/practice/yijinjing/yijinjing.md
    #     - 少林内劲一指禅: human-body/practice/neijinyizhichan/neijinyizhichan.md
    # - 心:
    #   - 神经系统: # 宏观层面、介观层面、微观层面
    #     - 人体神经系统: nervous-system/theory/nervous-system/nervous-system.md
    #     - 大脑的功能框架: nervous-system/theory/brain-functional-architecture/brain-functional-architecture.md
        # - 2.1.2 奖赏回路: jiangshanghuilu.md
        # - 2.1.3 基底节: jidijie.md
        # - 2.1.4 镜像神经元: jingxiangshenjingyuan.md
        # - 2.1.5 默认网络: morenwangluo.md
        # - 2.1.6 注意: zhuyi.md
  - 未来篇: 
    - 未来人类分化类型: futrue/human-futrue.md
  - 同道中人:
      - 前552-[春秋]孔子: ancient-sages\-551-kongzi.md
      - 前520-[古印度]乔达摩·悉达多: ancient-sages\-520-gautama.md
      - 前384-[古希腊]亚里士多德: ancient-sages\-384-Aristotle.md
      - 602-[唐朝]唐玄奘: ancient-sages\602-tangxuanzang.md
      - 1518-[明朝]李时珍: ancient-sages\1518-lishizhen.md
      - 1596-[法国]笛卡尔: ancient-sages\1596-Descartes.md
      - 1643-[英国]牛顿: ancient-sages\1643-newton.md
      - 1724-[德国]康德: ancient-sages\1724-Kant.md
      - 1893-[近现代中国]毛泽东: ancient-sages\1893-maozedong.md
  # - 探索者名录: ancient-sages.md
    # - 中国: zhongguo.md # 老子、孔子、...
    # - 西方: xifang.md # 笛卡尔、牛顿、...
    # - 印度: yindu.md # 佛祖、...


# Theme 主题设置
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.tabs.sticky # 固定导航条
    - navigation.expand
    
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
      # Toggle light mode
      - scheme: default
        primary: white
        accent: red
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Toggle dark mode
      - scheme: slate
        primary: black
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to light mode